# Generated by Django 4.2.25 on 2025-10-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachment_encrypted",
            field=models.FileField(blank=True, null=True, upload_to="encrypted/"),
        ),
    ]
