# Generated by Django 4.2.25 on 2025-10-30 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(upload_to="uploads/")),
                (
                    "container_image",
                    models.ImageField(blank=True, null=True, upload_to="containers/"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("size_original", models.BigIntegerField(null=True)),
                ("size_cipher", models.BigIntegerField(null=True)),
                ("size_container", models.BigIntegerField(null=True)),
                ("time_sign_ms", models.FloatField(null=True)),
                ("time_encrypt_ms", models.FloatField(null=True)),
                ("time_stego_ms", models.FloatField(null=True)),
                ("success_restore", models.BooleanField(default=False)),
                ("signature_valid", models.BooleanField(default=False)),
            ],
        ),
    ]
