# Generated by Django 4.2.25 on 2025-10-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filerecord",
            name="nonce",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filerecord",
            name="salt",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
