# Generated by Django 4.2.25 on 2025-10-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protector", "0002_filerecord_nonce_filerecord_salt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filerecord",
            name="created_at",
        ),
        migrations.AddField(
            model_name="filerecord",
            name="cipher_bytes",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filerecord",
            name="signature_bytes",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filerecord",
            name="size_cipher",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="filerecord",
            name="size_container",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="filerecord",
            name="size_original",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="filerecord",
            name="time_encrypt_ms",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="filerecord",
            name="time_sign_ms",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="filerecord",
            name="time_stego_ms",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="filerecord",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
