# Generated by Django 4.2.25 on 2025-10-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "protector",
            "0003_remove_filerecord_created_at_filerecord_cipher_bytes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="filerecord",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
